### ISSUE TITLE
Full resolution images and zooming feature

### ISSUE THREAD

**Issue by biprav** [monkeymademe/picamera2-WebUI-Lite#17]
This camera web interface is amazing. Kudos to you for developing such a great interface.
I just want to give some opinions. Is it possible to capture the images in full resolution? I have a 12 MP v3 camera and I want to capture the images in full 12 MP resolution. Also, is it possible to add a slider for zooming so that we can zoom onto the image preview to get an enlarged view of the live image?

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome

**Comment by monkeymademe** [comment]
First off I will answer the zooming feature: 

What you are looking for is the scaler crop settings... Admittedly not the best UI but currently its working - This is on my list for improvements. I would like do exactly what you describe.

Resolution is a little more tricky:

Currently I am sticking to the available sensor modes determined by picamera2 (and the sensor) for the V3 we have the following modes available 

 [{'bit_depth': 10,
  'crop_limits': (768, 432, 3072, 1728),
  'exposure_limits': (9, None),
  'format': SRGGB10_CSI2P,
  'fps': 120.13,
  'size': (1536, 864),
  'unpacked': 'SRGGB10'},
 {'bit_depth': 10,
  'crop_limits': (0, 0, 4608, 2592),
  'exposure_limits': (13, 77208384, None),
  'format': SRGGB10_CSI2P,
  'fps': 56.03,
  'size': (2304, 1296),
  'unpacked': 'SRGGB10'},
 {'bit_depth': 10,
  'crop_limits': (0, 0, 4608, 2592),
  'exposure_limits': (26, 112015443, None),
  'format': SRGGB10_CSI2P,
  'fps': 14.35,
  'size': (4608, 2592),
  'unpacked': 'SRGGB10'}]
  
It's basically setting things like the crop limits and FPS (amongst other things). At the moment the interface is selecting the middle sensor mode but again its on my list to have it possible to set the mode and restart the stream and have everything work.

If you need full resolution now and are happy to tinker in the code.

In app.py line 22 is currently:

`mode = picam2.sensor_modes[1]`

Change that to 2 instead of 1:

`mode = picam2.sensor_modes[2]`

This is untested so please be aware it might drop frames or crash.

(if its fine let me know ;-))

**Comment by biprav** [comment]
> First off I will answer the zooming feature:
> 
> What you are looking for is the scaler crop settings... Admittedly not the best UI but currently its working - This is on my list for improvements. I would like do exactly what you describe.
> 
> Resolution is a little more tricky:
> 
> Currently I am sticking to the available sensor modes determined by picamera2 (and the sensor) for the V3 we have the following modes available
> 
> [{'bit_depth': 10, 'crop_limits': (768, 432, 3072, 1728), 'exposure_limits': (9, None), 'format': SRGGB10_CSI2P, 'fps': 120.13, 'size': (1536, 864), 'unpacked': 'SRGGB10'}, {'bit_depth': 10, 'crop_limits': (0, 0, 4608, 2592), 'exposure_limits': (13, 77208384, None), 'format': SRGGB10_CSI2P, 'fps': 56.03, 'size': (2304, 1296), 'unpacked': 'SRGGB10'}, {'bit_depth': 10, 'crop_limits': (0, 0, 4608, 2592), 'exposure_limits': (26, 112015443, None), 'format': SRGGB10_CSI2P, 'fps': 14.35, 'size': (4608, 2592), 'unpacked': 'SRGGB10'}]
> 
> It's basically setting things like the crop limits and FPS (amongst other things). At the moment the interface is selecting the middle sensor mode but again its on my list to have it possible to set the mode and restart the stream and have everything work.
> 
> If you need full resolution now and are happy to tinker in the code.
> 
> In app.py line 22 is currently:
> 
> `mode = picam2.sensor_modes[1]`
> 
> Change that to 2 instead of 1:
> 
> `mode = picam2.sensor_modes[2]`
> 
> This is untested so please be aware it might drop frames or crash.
> 
> (if its fine let me know ;-))

Thanks for the prompt response.
I changed the parameter to 2 from 1 in the python code but still the resolution is same, that is it is capturing images in 1280 x 720 resolution.  Can any changes be made to capture the images in the maximum resolution of 4608 x 2592. 
Kindly help me out. Thank you.

**Comment by monkeymademe** [comment]
Sorry thats my bad... 1st setting the sensor mode is working at full resolution which is good to know

But also the size has to be added into the following line 21: 

`video_config = picam2.create_video_configuration(main={'size': mode['size']}, sensor={'output_size': mode['size'], 'bit_depth': mode['bit_depth']})`

Its adding this : `main={'size': mode['size']},`

That should max resolution if you set the mode to 2... BUT..... if you wanted a custom resolution like 800x600 for example you could put this instead

`main={'size': (800, 600)},`

should look like this in the end

`video_config = picam2.create_video_configuration(main={'size': (800, 600)}, sensor={'output_size': mode['size'], 'bit_depth': mode['bit_depth']})`

.... having said all that this is a hacky temp solution so I will be looking for something better ;-)

**Comment by biprav** [comment]
Lines 21 to 23 in the code is
`main_stream` = {"size": half_resolution}
mode = picam2.sensor_modes[2]
video_config = picam2.create_video_configuration(sensor={'output_size': mode['size'], 'bit_depth': `mode['bit_depth']})`

The line that you mentioned is not present in the code. Kindly let me know of any solution. Will be of great help. Thank you.

**Comment by monkeymademe** [comment]
> video_config = picam2.create_video_configuration(sensor={'output_size': mode['size'], 'bit_depth': mode['bit_depth']})`

There you go thats the line... change it to 

`video_config = picam2.create_video_configuration(main={'size': mode['size']}, sensor={'output_size': mode['size'], 'bit_depth': mode['bit_depth']})`

If you can wait a few more days I am working on a new config that will allow mode changes and capture resolutions

**Comment by monkeymademe** [comment]
So here is where we stand... 

- Digital zoom is taken care of with scalercrop (although room for improvement) its there
- Camera info page now you can set the sensor mode which has one issue... Max resolution has lower frame rate and at 14fps you see it, but its working
- In home page with the feed and settings there is now an option for Capture Resolution with the a list of resolutions. When you capture a still it will use the sensor mode resolution but this setting will additionally resize the image and save it.

I'll be honest I am not happy with the wording of the capture settings cause its not capturing the still at the set resolution but resizing so maybe expect that to look different at some point

But for your wish to max out the still resolution is possible now

https://github.com/monkeymademe/picamera2-WebUI-Lite/releases/tag/v0.0.3

**Comment by biprav** [comment]
Thank you so much for the prompt action on your part. I will use the updated interface now. I will let you know of any suggestions and additions that can be made to make the interface more versatile.

**Comment by monkeymademe** [comment]
You got me on a good day... This version is better (look out for dng) https://github.com/monkeymademe/picamera2-WebUI-Lite/releases/tag/v0.0.4

**Comment by biprav** [comment]
I just tried the new version. It is so good. The capture configuration is awesome. Thank you so much for the addition. Choosing the highest resolution of 4608 x 2592 does reduce the frame rate and makes the image preview a bit slow. But the new addition is such a good one. Just another request. Whenever you get time please add a feature for digital zoom. I know the scaler crop feature is available but a slider for digital zoom in real time would be handy. Thank you.

**Comment by biprav** [comment]
Hi. I'm using the UI and loving every bit of it. Just wanted to know whether you plan on adding a slider for the zooming feature just like in a smartphone camera app?
Also, can you add ISO,shutter speed in options that are similar to that of a smartphone camera?

Thanks a lot.
