### ISSUE TITLE
Add a LICENSE

### ISSUE THREAD

**Issue by andypiper** [monkeymademe/picamera2-WebUI-Lite#24]
I've just sent a tiny pull request to fix a typo in the UI (noted from a screenshot in Les Pounder's article on Tom's Hardware!).

Would you be willing to add a LICENSE to the repository that indicates whether or not it is Open Source? Thanks!

**Comment by monkeymademe** [comment]
Looking into that.. was not sure what I should put because I have a copy of bootstrap in there

**Comment by monkeymademe** [comment]
MIT done, thanks for pointing that out
